project:
  type: book

book:
  title: "Intro to Terminal & Git for R"
  author: "Anastasia Goodwin, edited by Christian McDonald"
  date: "May 2025"
        
  chapters:
    - index.qmd
    - how-to-use.qmd
    - text: "---"  
    - part: "Intro to Terminal"
    - text: "---"
    - part: "Introduction"
      chapters:
      - terminal/welcome.qmd
      - terminal/introduction.qmd
    - part: "Terminal basics"
      chapters:
      - terminal/moving-around.qmd
      - terminal/making-files-folders.qmd
    - part: "Tips & tricks"
      chapters:
      - terminal/tips-tricks.qmd
    - part: "Appendices"
      chapters:
      - terminal/appendices/a-troubleshooting.qmd
      - terminal/appendices/a-quick-reference.qmd
      - terminal/appendices/a-change-terminal-color.qmd
    - text: "---"
    - part: "Intro to Git"
    - text: "---"
    - part: "Installation"
      chapters:
      - intro-to-git/welcome.qmd
      - intro-to-git/introduction-to-git.qmd
      - intro-to-git/install-and-setup.qmd
    - part: "Git basics"
      chapters:
       - intro-to-git/make-git-project.qmd
       - intro-to-git/add-files.qmd
       - intro-to-git/pushing-to-github.qmd
       - intro-to-git/updating-your-repo.qmd
    - part: "Advanced: collaborating with others"
      chapters:
      - intro-to-git/collaboration-setup-and-basic-workflow.qmd
      - intro-to-git/dealing-with-conflicts.qmd
      - intro-to-git/working-with-branches.qmd
      - intro-to-git/pull-requests.qmd
    - part: "Appendices"
      chapters:
      - intro-to-git/appendices/a-troubleshooting.qmd
      - intro-to-git/appendices/a-quick-reference.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-overflow: wrap
    css: styles.css