project:
  type: book
  output-dir: docs
  
book:
  title: "Git for R"
  author: "Christian McDonald"
  date: "September 2024"
  chapters:
    - index.qmd
    - part: "Intro to Git"
    - part: "Installation"
      chapters:
      - intro-to-git/00-introduction.qmd
      - intro-to-git/01-install-and-setup.qmd
    - part: "Git basics"
      chapters:
       - intro-to-git/02-making-a-repo.qmd
       - intro-to-git/03-add-files.qmd
       - intro-to-git/04-pushing-to-github.qmd
       - intro-to-git/05-updating-your-repo.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-overflow: wrap