project:
  type: book
  output-dir: docs
  
book:
  title: "Git for R"
  author: "Christian McDonald"
  date: "September 2024"
        
  chapters:
    - index.qmd
    - part: "Intro to Terminal"
    - text: "---"
    - part: "Part 1: Introduction"
      chapters:
      - terminal/00-introduction.qmd
    - part: "Part 2: Terminal basics"
      chapters:
      - terminal/01-moving-around.qmd
      - terminal/02-making-files-folders.qmd
    - part: "Part 3: Tips, tricks, troubleshooting"
      chapters:
      - terminal/03-tips-tricks.qmd
      - terminal/04-troubleshooting.qmd
      - terminal/05-glossary.qmd
    - text: "---"
    - part: "Intro to Git"
    - text: "---"
    - part: "Installation"
      chapters:
      - intro-to-git/00-introduction.qmd
      - intro-to-git/01-introduction-to-git.qmd
      - intro-to-git/02-install-and-setup.qmd
    - part: "Git basics"
      chapters:
       - intro-to-git/03-make-git-project.qmd
       - intro-to-git/04-add-files.qmd
       - intro-to-git/05-pushing-to-github.qmd
       - intro-to-git/06-updating-your-repo.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-overflow: wrap