project:
  type: book
  output-dir: docs
  
book:
  title: "Intro to Terminal & Git for R"
  author: "Anastasia Goodwin, edited by Christian McDonald"
  date: "May 2025"
        
  chapters:
    - index.qmd
    - text: "---"  
    - part: "Intro to Terminal"
    - text: "---"
    - part: "Introduction"
      chapters:
      - terminal/00-introduction.qmd
    - part: "Terminal basics"
      chapters:
      - terminal/01-moving-around.qmd
      - terminal/02-making-files-folders.qmd
    - part: "Tips, tricks, troubleshooting"
      chapters:
      - terminal/03-tips-tricks.qmd
      - terminal/04-troubleshooting.qmd
      - terminal/05-glossary.qmd
    - text: "---"
    - part: "Intro to Git"
    - text: "---"
    - part: "Installation"
      chapters:
      - intro-to-git/introduction.qmd
      - intro-to-git/introduction-to-git.qmd
      - intro-to-git/install-and-setup.qmd
    - part: "Git basics"
      chapters:
       - intro-to-git/make-git-project.qmd
       - intro-to-git/add-files.qmd
       - intro-to-git/pushing-to-github.qmd
       - intro-to-git/updating-your-repo.qmd
    - part: "Advanced: collaborating with others"
      chapters:
      - intro-to-git/setup-and-basic-workflow.qmd
      - intro-to-git/dealing-with-conflicts.qmd
      - intro-to-git/working-with-branches.qmd
      - intro-to-git/pull-requests.qmd
    - part: "Appendices"
      chapters:
      - intro-to-git/quick-reference.qmd
      - intro-to-git/troubleshooting.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-overflow: wrap