---
title: "Welcome"
---

Welcome to the **Intro to Git** guide! We hope this guide will be a resource for you to learn the basics of working with version control for the first time.

## Who is this guide for? {.unnumbered}

This guide is for students who know some R and want to learn Git and GitHub to manage and collaborate on R projects (especially Quarto ones). It assumes little-to-no hands-on terminal experience but will encourage building confidence over time by interacting with Github through the command line.

Students who are brand new to the terminal may also find it helpful to go through the [**Intro to Terminal**](/terminal/welcome.html) section of this book before working through this guide.

## How to use this book {.unnumbered}

Before you dive in, we want to highlight a few things about how we've structured the guide to ensure you get the most of your learning experience.

As you work through the guide, we strongly recommend that you do the following:

1. **Type your commands:** Getting used to writing git commands in the command line is key to learning and remembering workflows. Though many of the code blocks in this books allow you to copy the code inside, please try to type it yourself (at least on the first try). You can always copy if you run into errors.

3. **Do the mini exercises:** There will be small exercises throughout this guide to reinforce learning and get you more comfortable working in the Terminal and Git. Learning to code is largely done through *doing*, so we highly recommend you take the time to do all of them.

2. **Do the chapters in order**: The mini exercises and content in this book are structured to build upon each other. Your first time through, we recommend you complete each chapter along with the mini-exercises in chronological order to ensure you don't miss steps you need later on. 

4. **Read the terminology notes:** Throughout this guide, there will be several callout boxes titled "terminology notes". These callouts will be used to explain key terms – especially those used interchangeably – that may be confusing to new programmers. We recommend you take the time to read them because knowing the language coders use will help when reading documentation and when seeking help in online spaces like Stack Overflow.


## Prerequisites {.unnumbered}

Before we move on to working with Git and Github, we need to make sure you have what you need to successfully complete the exercises in this guide. The guide assumes you already have the following installed on your computer:

1.  [R](https://cloud.r-project.org/)
2.  [RStudio](https://posit.co/download/rstudio-desktop/)
3.  [Quarto](https://quarto.org/docs/get-started/)

If you are missing any these, please go to the links listed and make sure to install before moving on to the next chapter!

If you need additional help with installing, you may find it helpful to reference the steps to set up your machine in the "Install Party" chapter of the [**Reporting with Data in R**](https://utdata.github.io/rwdir/install.html) book by Professor Christian McDonald. 
